name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"
        cache: true

    - name: Build
      run: |
        CGO_ENABLED=0 GOOS=linux go build -o bin/crude-amd64 .
        CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o bin/crude-arm64 .
