name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: |
        CGO_ENABLED=0 GOOS=linux go build -o bin/crude-amd64 .
        CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o bin/crude-arm64 .

#     - name: Create release
#       id: create_release
#       uses: actions/create-release@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         tag_name: ${{ github.event.inputs.tag }}
#         draft: false
#         prerelease: false

#     - name: Upload binaries to release
#       uses: alexellis/upload-assets@0.2.2
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         asset_paths: '["./bin/crude*"]'

    # - name: Upload a Build Artifact
    #   uses: actions/upload-artifact@v3.1.0
    #   with:
    #     # Artifact name
    #     name: crude
    #     path: bin/*

